# READY FOR QA
# Feature: TrainingPlan model
# What was built: Full TrainingPlan model with JSON plan data and Pak Har notes
# Edge cases to consider:
#   - plan_data and pak_har_notes are JSON columns — use JSON type annotation
#   - is_active flag — only one plan should be active per user at a time (enforced in service layer)
#   - week_start_date — the Monday of the plan week, used for deduplication
#   - Only one active plan per user enforced by service layer, not DB constraint

from datetime import datetime, date

from sqlalchemy import String, DateTime, Boolean, Date, JSON, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, relationship

from models.base import Base


class TrainingPlan(Base):
    """
    TrainingPlan model — a 7-day structured running plan generated by Pak Har.

    plan_data example:
        {"monday": {"type": "rest"}, "tuesday": {"type": "easy", "duration_min": 30, "notes": "steady pace"}}
    pak_har_notes example:
        {"monday": "Rest day. You're not recovering faster by running on no sleep.", ...}
    """
    __tablename__ = "training_plans"

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id"), index=True)

    # The Monday of the plan week
    week_start_date: Mapped[date] = mapped_column(Date, index=True)

    # Full 7-day plan as JSON
    plan_data: Mapped[dict] = mapped_column(JSON)
    # Pak Har's notes for each day
    pak_har_notes: Mapped[dict] = mapped_column(JSON)

    # Only one active plan per user at a time
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, index=True)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, default=datetime.utcnow, onupdate=datetime.utcnow
    )

    # Relationships
    user: Mapped["User"] = relationship("User", back_populates="training_plans")