"""
Pydantic v2 schemas for the GET /insights endpoint.

InsightsRead is the sole response model — it carries aggregated multi-week
trend stats and Pak Har's commentary generated by Ollama.
"""

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict


class InsightsRead(BaseModel):
    """Response schema for GET /insights."""

    model_config = ConfigDict(from_attributes=True)

    # Number of distinct ISO calendar weeks with at least one run in the 6-week window
    weeks_analyzed: int

    # Total distance / weeks_analyzed, rounded to 1 decimal place
    avg_weekly_km: float

    # Weighted average pace across all activities (moving_time_seconds / distance_km),
    # expressed in minutes per km, rounded to 2 decimal places
    avg_pace_min_per_km: float

    # Direction of pace change comparing first half vs second half of the window:
    # "improving" — second half faster by > 3 s/km
    # "declining" — second half slower by > 3 s/km
    # "stable"    — difference <= 3 s/km
    pace_trend: Literal["improving", "declining", "stable"]

    # (weeks with ≥ 1 run / 6) * 100, rounded to nearest integer
    consistency_pct: int

    # Pak Har's 2–3 sentence honest assessment + one concrete directive
    pak_har_commentary: str

    # UTC timestamp of when this response was generated
    generated_at: datetime
