// Activity feed — fake data, tabloid vibe. Dates stop just before the 12 Apr run
// from run-data.jsx, which is the "latest edition".

const ACTIVITIES = [
  {
    id: 'r-000412',
    latest: true,
    title: 'Sunday Easy',
    date: 'Sun 12 Apr 2026',
    dateShort: 'SUN 12 APR',
    distance_km: 10.4,
    time: '58:12',
    pace: '5:36',
    hr: 162, max_hr: 181,
    elev: 64,
    route: 'Senayan loop × 2',
    type: 'EASY',
    verdict_short: 'You went out too hard. Again.',
    verdict_tag: 'PACED POORLY',
    tone: 'critical',
  },
  {
    id: 'r-000411',
    title: 'Thursday Threshold',
    date: 'Thu 9 Apr 2026',
    dateShort: 'THU 9 APR',
    distance_km: 8.2,
    time: '41:04',
    pace: '5:00',
    hr: 171, max_hr: 184,
    elev: 28,
    route: 'GBK outer',
    type: 'TEMPO',
    verdict_short: 'Second rep was the real one. Build on that.',
    verdict_tag: 'HELD THE LINE',
    tone: 'neutral',
  },
  {
    id: 'r-000410',
    title: 'Tuesday Easy',
    date: 'Tue 7 Apr 2026',
    dateShort: 'TUE 7 APR',
    distance_km: 6.1,
    time: '35:40',
    pace: '5:50',
    hr: 154, max_hr: 168,
    elev: 18,
    route: 'Kemang 3k loop × 2',
    type: 'EASY',
    verdict_short: 'Boring. Boring is correct.',
    verdict_tag: 'ON PLAN',
    tone: 'good',
  },
  {
    id: 'r-000409',
    title: 'Sunday Long',
    date: 'Sun 5 Apr 2026',
    dateShort: 'SUN 5 APR',
    distance_km: 15.6,
    time: '1:32:18',
    pace: '5:55',
    hr: 159, max_hr: 175,
    elev: 92,
    route: 'Sudirman — Dukuh Atas — Senayan',
    type: 'LONG',
    verdict_short: 'Last 3km slower. Eat sooner next time.',
    verdict_tag: 'FUELING',
    tone: 'neutral',
  },
  {
    id: 'r-000408',
    title: 'Friday Shakeout',
    date: 'Fri 3 Apr 2026',
    dateShort: 'FRI 3 APR',
    distance_km: 4.2,
    time: '24:56',
    pace: '5:56',
    hr: 148, max_hr: 158,
    elev: 10,
    route: 'Block × 4',
    type: 'EASY',
    verdict_short: 'Nothing to analyse. That was the point.',
    verdict_tag: 'RESTRAINED',
    tone: 'good',
  },
  {
    id: 'r-000407',
    title: 'Tuesday Intervals',
    date: 'Tue 31 Mar 2026',
    dateShort: 'TUE 31 MAR',
    distance_km: 7.4,
    time: '39:50',
    pace: '5:22',
    hr: 168, max_hr: 186,
    elev: 22,
    route: 'GBK track · 6×800',
    type: 'INTERVAL',
    verdict_short: 'Sixth rep fell apart. Not a disaster. Still a lesson.',
    verdict_tag: 'FADED LATE',
    tone: 'neutral',
  },
  {
    id: 'r-000406',
    title: 'Sunday Long',
    date: 'Sun 29 Mar 2026',
    dateShort: 'SUN 29 MAR',
    distance_km: 14.0,
    time: '1:22:40',
    pace: '5:54',
    hr: 158, max_hr: 172,
    elev: 76,
    route: 'Senayan loop × 3',
    type: 'LONG',
    verdict_short: 'Steady. No heroics. Good.',
    verdict_tag: 'STEADY',
    tone: 'good',
  },
  {
    id: 'r-000405',
    title: 'Skipped',
    date: 'Thu 26 Mar 2026',
    dateShort: 'THU 26 MAR',
    distance_km: 0,
    time: '—',
    pace: '—',
    hr: null, max_hr: null,
    elev: 0,
    route: '—',
    type: 'MISSED',
    verdict_short: 'The rain was not the reason. You already know that.',
    verdict_tag: 'NO SHOW',
    tone: 'critical',
  },
];

window.ACTIVITIES = ACTIVITIES;
