"""add verdict fields to activities

Revision ID: 45cea3127645
Revises: b1c2d3e4f5a6
Create Date: 2026-04-25 19:10:00.599112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45cea3127645'
down_revision: Union[str, None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('verdict_short', sa.String(length=120), nullable=True))
    op.add_column('activities', sa.Column('verdict_tag', sa.String(length=40), nullable=True))
    op.add_column('activities', sa.Column('tone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'tone')
    op.drop_column('activities', 'verdict_tag')
    op.drop_column('activities', 'verdict_short')
    # ### end Alembic commands ###
