"""add composite index user_id activity_date

Revision ID: e1f9d71fd3f0
Revises: d4e5f6a7b8c9
Create Date: 2026-05-13 21:07:22.491224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1f9d71fd3f0'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_activity_user_date', 'activities', ['user_id', 'activity_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_activity_user_date', table_name='activities')
    # ### end Alembic commands ###
